Repository hpi-schul-cloud/dof_app_deploy, pull requests merged in 2022-08, with the labels that each got.

#323 N21-207 Added env for nextcloud
  ansible/group_vars/all/config.yml
  ansible/group_vars/nbc/instance_cfg.yml
  ansible/host_vars/nbc_host/cfg.yml
  ansible/host_vars/prod-nbc/cfg.yml
  ansible/host_vars/ref-nbc/cfg.yml
Labels: waiting for review

#315 N21-185-activate-iserv-login-in-production
  ansible/host_vars/prod-nbc/cfg.yml
Labels: is blocked

#334 N21-182 bbb waiting room now set to true in all nbc instances
  ansible/host_vars/prod-nbc/cfg.yml
Labels: ready to merge, waiting for review

#328 EW-292 Add OIDC identity provider mock to auto deployment
  ansible/group_vars/all/config.yml
  ansible/group_vars/all/with.yml
  ansible/group_vars/develop/oidcmock.yml
  ansible/group_vars/develop/with.yml
  ansible/playbook.yml
  ansible/roles/erwin-idm/templates/secret.yml.j2
  ansible/roles/oidcmock/README.md
  ansible/roles/oidcmock/meta/main.yml
  ansible/roles/oidcmock/tasks/main.yml
  ansible/roles/oidcmock/templates/configmap.yml.j2
  ansible/roles/oidcmock/templates/deployment.yml.j2
  ansible/roles/oidcmock/templates/ingress.yml.j2
  ansible/roles/oidcmock/templates/onepassword.yml.j2
  ansible/roles/oidcmock/templates/secret.yml.j2
  ansible/roles/oidcmock/templates/svc.yml.j2
Labels: waiting for review
